#!/bin/bash
export SWAP_DATADIR=$HOME/coinswaps
if [[ $USER == amnesia ]]; then
    export SWAP_DATADIR=$HOME/Persistent/coinswaps
fi

# Colors
red="printf \e[31;1m"
green="printf \e[32;1m"
nocolor="printf \e[0m"

# Check if basicswap is running
if [[ -f $SWAP_DATADIR/particl/particl.pid ]]; then
    bsx_pid=$(cat $SWAP_DATADIR/particl/particl.pid)
    if [[ $bsx_pid ]]; then
        bsx_run=$(pgrep particld | grep $bsx_pid)
        if [[ $bsx_run ]]; then
            $red"\nError: BasicSwapDEX is running.\n"; $nocolor
            exit
        fi
    fi
fi

export disablecoin="$1"
. $SWAP_DATADIR/venv/bin/activate
$HOME/.local/bin/bsx/removecoin.sh
