#!/bin/bash
source $HOME/.local/bin/bsx/shared.sh

is_tails

# Check if basicswap is running
if [[ -f $SWAP_DATADIR/particl/particl.pid ]]; then
    bsx_pid=$(cat $SWAP_DATADIR/particl/particl.pid)
    bsx_run=$(pgrep particld | grep $bsx_pid)
    if ! [[ $bsx_run ]]; then
        $red"\nError: BasicSwapDEX must be running.\n"; $nocolor
        exit
    fi
else
    $red"\nError: BasicSwapDEX must be running.\n"; $nocolor
    exit
fi

cp $HOME/.local/bin/bsx/placeorders/* $SWAP_DATADIR/basicswap/scripts/.
cd $SWAP_DATADIR/basicswap/scripts/

./placeorders.sh
