#!/bin/bash
source $HOME/.local/bin/bsx/shared.sh

if [[ $1 = "--force" ]]; then
    green "Force updating"
else
    is_running
fi
is_tails

# Cleanup old version
if [ -f /usr/local/bin/bsx/update.sh ]; then
    /usr/local/bin/bsx/update.sh
    cd /usr/local/bin
    sudo rm -rf basicswap-bash bsx*
fi

# Download updated scripts
echo "Updating basicswap-bash scripts" && sleep 1

cd $SWAP_DATADIR/basicswap || {
    red "Cannot find datadir. Update failed"
    exit 1
}
if [[ -d basicswap-bash ]]; then
    cd basicswap-bash
    git pull || {
        red "Failed to update repo. Cancelling update."
        exit 1
    }
else
    git clone https://github.com/nahuhh/basicswap-bash || {
        red "Failed to clone repo. Cancelling update."
        exit 1
    }
    cd basicswap-bash
fi

# Cleanup old
[[ -f $HOME/.local/bin/install.sh ]] && rm $HOME/.local/bin/install.sh

# Update BasicSwap, coincurve and coin cores
./bsx/update.sh
