name: ci

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
    types:
      - opened
      - reopened
      - syncronize
  push:
#    branches:
#      - master
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v4
    - name: Install dependencies
      run: |
        npm install prettier prettier-plugin-sh --save-dev
    - name: Run Prettier
      run: |
        npx prettier basicswap-* bsx-* bsx/*.sh "!(bsx-update)" -c -w || true
        [[ $(git diff) ]] && git diff && exit 1 || exit 0

  build-macos:
    needs: formatting
    name: 'macOS (brew)'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout/@v4
    - name: Install basicswap-bash
      run: |
        ./basicswap-install.sh --new --tor --internal --regtest
    - name: Run bsx-update
      run: |
        bsx-update
    - name: Run basicswap-bash
      run: |
        timeout 30s ./basicswap-bash --regtest || [[ $? -eq 124 ]] && exit 0

  build-arch:
    needs: formatting
    name: 'Arch Linux'
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - uses: actions/checkout/@v4
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S sudo git --noconfirm
    - name: Install basicswap-bash
      run: |
        ./basicswap-install.sh --new --tor --internal --regtest
    - name: Run basicswap-bash
      run: |
        timeout 30s ./basicswap-bash --regtest || [[ $? -eq 124 ]] && exit 0

  build-fedora:
    needs: formatting
    name: 'Fedora'
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - uses: actions/checkout/@v4
    - name: Install dependencies
      run: |
        dnf install git procps-ng -y
    - name: Install basicswap-bash
      run: |
        ./basicswap-install.sh --new --tor --internal --regtest
    - name: Run bsx-update
      run: |
        source ~/.bash_profile && \
        bsx-update
    - name: Run basicswap-bash
      run: |
        timeout 30s ./basicswap-bash --regtest || [[ $? -eq 124 ]] && exit 0

  build-ubuntu:
    needs: formatting
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v4
    - name: Install basicswap-bash
      run: |
        ./basicswap-install.sh --new --tor --internal --regtest
    - name: Run bsx-update
      run: |
        bsx-update
    - name: Run basicswap-bash
      run: |
        timeout 30s ./basicswap-bash --regtest || [[ $? -eq 124 ]] && exit 0
